### ISSUE TITLE
ModuleNotFoundError: No module named 'xdg.BaseDirectory'

### ISSUE THREAD

**Issue by DemonRx** [henrywoo/kazam-screen-recorder#3]
Running kazam version 1.5.5

OS/version:
Distributor ID:	Ubuntu
Description:	Ubuntu 21.10
Release:	21.10
Codename: impish

```python
mesa: for the -simplifycfg-sink-common option: may only occur zero or one times!
/home/demon/.local/bin/kazam:32: PyGIWarning: Gtk was imported without specifying a version first. Use gi.require_version('Gtk', '4.0') before import to ensure that the right version gets loaded.
  from gi.repository import Gtk
WARNING Kazam - Failed to correctly detect operating system.
Traceback (most recent call last):
  File "/home/demon/.local/bin/kazam", line 147, in <module>
    from kazam.app import KazamApp
  File "/home/demon/.local/lib/python3.9/site-packages/kazam/app.py", line 36, in <module>
    from kazam.backend.prefs import *
  File "/home/demon/.local/lib/python3.9/site-packages/kazam/backend/prefs.py", line 26, in <module>
    from xdg.BaseDirectory import xdg_config_home
ModuleNotFoundError: No module named 'xdg.BaseDirectory'
```

**Comment by DemonRx** [comment]
After reinstalling the pyxdg python package and re-running kazam produces this output:

```python
mesa: for the -simplifycfg-sink-common option: may only occur zero or one times!
/home/demon/.local/bin/kazam:32: PyGIWarning: Gtk was imported without specifying a version first. Use gi.require_version('Gtk', '4.0') before import to ensure that the right version gets loaded.
  from gi.repository import Gtk
WARNING Kazam - Failed to correctly detect operating system.
/home/demon/.local/lib/python3.9/site-packages/kazam/backend/webcam.py:24: PyGIWarning: GUdev was imported without specifying a version first. Use gi.require_version('GUdev', '1.0') before import to ensure that the right version gets loaded.
  from gi.repository import GObject, GUdev
Traceback (most recent call last):
  File "/home/demon/.local/bin/kazam", line 147, in <module>
    from kazam.app import KazamApp
  File "/home/demon/.local/lib/python3.9/site-packages/kazam/app.py", line 36, in <module>
    from kazam.backend.prefs import *
  File "/home/demon/.local/lib/python3.9/site-packages/kazam/backend/prefs.py", line 562, in <module>
    Gdk.CursorType.TOP_LEFT_CORNER,
  File "/home/demon/.local/lib/python3.9/site-packages/gi/overrides/__init__.py", line 32, in __getattr__
    return getattr(self._introspection_module, name)
  File "/home/demon/.local/lib/python3.9/site-packages/gi/module.py", line 123, in __getattr__
    raise AttributeError("%r object has no attribute %r" % (
AttributeError: 'gi.repository.Gdk' object has no attribute 'CursorType'
```

**Comment by DemonRx** [comment]
Attempting to start it with older versions of python also produces errors:

Python 2.5:
```python
python2.7 /home/demon/.local/bin/kazam
Traceback (most recent call last):
  File "/home/demon/.local/bin/kazam", line 26, in <module>
    import dbus
ImportError: No module named dbus
```

Python 3.5 :
```python
Traceback (most recent call last):
  File "/home/demon/.local/bin/kazam", line 26, in <module>
    import dbus
  File "/usr/lib/python3/dist-packages/dbus/__init__.py", line 73, in <module>
    import dbus.types as types
  File "/usr/lib/python3/dist-packages/dbus/types.py", line 8, in <module>
    from _dbus_bindings import (
ImportError: No module named '_dbus_bindings'
```

I'm wondering if the Python installation is somehow messed up after the Ubuntu upgrade to Impish ?

**Comment by DemonRx** [comment]
I was able to solve the issue with `AttributeError: 'gi.repository.Gdk' object has no attribute 'CursorType'`

Refer to https://forums.gentoo.org/viewtopic-p-8619813.html?sid=1b73402d78f28b295379b405812d9b1d

The problem seems that program not specify to use gtk:3 and if you have installed gtk:4 program fails to start.
Changing line 32 in /usr/bin/kazam from:

https://github.com/henrywoo/kazam-screen-recorder/blob/2859190b40b149800f0b0968a25aac6d6a24a408/bin/kazam#L32

To: 

```python
import gi
gi.require_version('Gtk', '3.0')
from gi.repository import Gtk
```

Will open a PR on this issue.
